### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by giankdiluvi** [ubc-stat-grad/ubc-stat-grad.github.io#1]
- [x] create/improve + add logo
- [x] discuss slack (not open to public i think)
- [x] add more van Eeden presenters
- [ ] link to fb group

**Comment by nikola-sur** [comment]
Should we add a link to the Facebook group? (Is there a FB group yet?)

**Comment by giankdiluvi** [comment]
There is (I just invited you) but no one really uses it. If we link to it, we might want to make the group more active - although I don't have the bandwidth for that =(
